language: cpp
os:
  - linux
  - osx
env:
  - XMAKE=qmake
  - XMAKE=cmake
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = osx ];   then brew update; fi
install:
  - if [ $TRAVIS_OS_NAME = linux ] && [ $XMAKE = cmake ]; then sudo apt-get install -y cmake; fi
  - if [ $TRAVIS_OS_NAME = linux ];                       then sudo apt-get install -y libqt4-dev qt4-qmake; fi
  - if [ $TRAVIS_OS_NAME = osx ]   && [ $XMAKE = cmake ]; then brew install cmake; fi
  - if [ $TRAVIS_OS_NAME = osx ];                         then brew install qt; fi
script:
  - $XMAKE . && make
