language: objective-c
os: osx
matrix:
  include:
    - compiler: clang
      env:
        - XMAKE=qmake
    - compiler: clang
      env:
        - XMAKE=cmake
        - XMAKE_OPTIONS="."
    - compiler: clang
      env:
        - XMAKE=qmake
        - XMAKE_OPTIONS="NON_MAC_WIDGETS=1"
    - compiler: gcc
      env:
        - XMAKE=cmake
        - XMAKE_OPTIONS=". -DNON_MAC_WIDGETS=ON"
        - CC=gcc-4.9
        - CXX=g++-4.9
before_install:
  - brew update
install:
  - brew install qt
script:
  - $XMAKE $XMAKE_OPTIONS && make
